---
- hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  include_vars: vault.yml
  handlers:
  - name: restart sshd
      service:
      name: sshd
      state: restarted
  - name: restart nginx
      name: nginx
      state: restarted  
  tasks:
  - name: create and configure a new ansible user
    user:
     name: ansible
     password: {{ ansible_user_pass }}
     shell: /bin/bash
    notify: restart sshd

- hosts: webservers
  tasks:
  - name: ensure nginx is at the latest version
    apt:
      name: nginx
      state: latest
      update_cache: yes
    when: "ansible_facts['os_family'] == 'Debian'"  
  - name: write the nginx index file
    copy:
      src: /files
      dest: /etc/httpd.conf
    when: "ansible_facts['os_family'] == 'Debian'"  

- hosts: dbservers
  remote_user: root

  tasks:
  - name: ensure postgresql is at the latest version
    yum:
      name: postgresql
      state: latest
    when: "ansible_facts['os_family'] == 'RedHat'"  
  - name: ensure that postgresql is started
    service:
      name: postgresql
      state: started
    when: "ansible_facts['os_family'] == 'RedHat'"   

