postgresql_databases:
    - name: production
      encoding: 'UTF-8'
      lc_collate: 'en_US.UTF-8'
      lc_ctype: 'en_US.UTF-8'
      template: 'template0'
      state: present
    - name: production2
      encoding: 'UTF-8'
      lc_collate: 'en_US.UTF-8'
      lc_ctype: 'en_US.UTF-8'
      template: 'template0'
      state: present
postgresql_users:
    - name: "{{ proddbuser }}"
      password: "{{ proddbpassword }}"
      state: present