postgresql_databases:
    - name: staging
      encoding: 'UTF-8'
      lc_collate: 'en_US.UTF-8'
      lc_ctype: 'en_US.UTF-8'
      template: 'template0'
      state: present
    - name: staging2
      encoding: 'UTF-8'
      lc_collate: 'en_US.UTF-8'
      lc_ctype: 'en_US.UTF-8'
      template: 'template0'
      state: present
postgresql_users:
    - name: "{{ stagdbuser }}"
      password: "{{ stagdbpassword }}"
      state: present      