---
# tasks file for ansible-role-users
  - name: create and configure new users
    user:
     name: "{{ item.username }}"
     password: "{{ item.password if item.password is defined else '!' }}"
     shell: "{{ item.shell if item.shell is defined else users_default_shell }}"
     update_password: "{{ item.update_password | default(omit) }}"
     home: "{{ item.home | default('/home/' + item.username) }}"
     append: "{{ item.append | default(omit) }}"
    with_items: "{{ users }}" 
    notify: restart sshd